{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = VERSION %}
{% set project = pyproject['project'] %}

package:
  name: read5
  version: {{ version }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -v .
  number : 0

requirements:
  host:
    - python
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    {% for dep in project['optional-dependencies']['test'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - pytest

about:
  home: {{ project['urls']['repository'] }}
  summary: {{ project['description'] }}
  license: {{ pyproject.get('license') }}
  license_file: LICENSE
  description: |
    {{ project['description'] }}

extra:
  recipe-maintainers:
    - JannesSP